apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c9n4wd7zd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c9n4wd7zd-go 
  name: c9n4wd7zd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c9n4wd7zd-go 
